<a href="https://colab.research.google.com/github/souhirkammoun/MultilayerPerceptronExamples/blob/master/MLPinKeraswithIRISdataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
#NB1 : import our data with the following python code.
#required library which holes the iris dataset
from sklearn.datasets import load_iris
import numpy as np
#load the iris dataset
iris = load_iris()
#our inputs will contain 4 features
X = iris.data[:, 0:4]
#the labels are the following
y = iris.target
#print the distinct y labels
print(np.unique(y))

#NB2: The last line prints the distinct labels for each of the 3 species. You should be seeing these labels:  [0 1 2] 

[0 1 2]


In [0]:
#NB3 :  In order for our classifier to work correctly we will first one hot encode our y vector 
#One Hot Encode our Y:
from sklearn.preprocessing import LabelBinarizer
encoder = LabelBinarizer()
Y = encoder.fit_transform(y)

In [4]:
#NB4 : Building our Model
#We will be now implementing a Multi-Layer Perceptron that contains 3 layers.
#Keras provides easy to use functionality to achieve this using its Sequential model.
#The Keras sequential model is a linear stack of layers. Keras provides different types of layers. 
#We will be using the Dense layer type which is a fully connected layer that implements the operation
#output = activation(dot(input, kernel) + bias). To train our network we will be using the Stochastic Gradient Descent optimizer.
from keras.models import Sequential #Sequential Models
from keras.layers import Dense #Dense Fully Connected Layer Type
from keras.optimizers import SGD #Stochastic Gradient Descent Optimizer

Using TensorFlow backend.


In [0]:
#NB5 : We will now create our network architecture. It will contain 3 layers. 

#Our first layer will have 4 inputs corresponding to the 4 features we will be utilizing from the iris dataset.
#For our second layer (hidden layer) we will be using 5 neurons.
#Our third layer, will provide our classifications. This layer contains 3 neurons, corresponding to the 3 classes that we are aiming to predict.
def create_network():
    model = Sequential()
    model.add(Dense(5, input_shape=(4,), activation='relu'))
    model.add(Dense(3, activation='softmax'))
        
    #stochastic gradient descent
    sgd = SGD(lr=0.001, decay=1e-6, momentum=0.9, nesterov=True)
    model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])
    return model

In [6]:
#NB6 :#Training our Model
#Once we have our model built, we compiled our model.
#To compile our model we need to provide a loss function and an optimizer.
#The optimizer we defined to be the Stochastic Gradient Descent with a learning rate of 0.001, decay of 0.000001 and momentum of 0.9. 
neural_network = create_network()
neural_network.fit(X,Y, epochs=500, batch_size=10)






Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/500





150/150 [==============================] - 1s 6ms/step - loss: 2.9108 - acc: 0.3067
Epoch 2/500
150/150 [==============================] - 0s 123us/step - loss: 1.3530 - acc: 0.2800
Epoch 3/500
150/150 [==============================] - 0s 138us/step - loss: 1.2853 - acc: 0.2000
Epoch 4/500
150/150 [==============================] - 0s 159us/step - loss: 1.2056 - acc: 0.1533
Epoch 5/500
150/150 [==============================] - 0s 132us/step - loss: 1.1687 - acc: 0.0867
Epoch 6/500
150/150 [==============================] - 0s 119us/step - loss: 1.1534 - acc: 0.2333
Epoch 7/500
150/150 [==============================] - 0s 147us/step - loss: 1.1252 - acc: 0.1467
Epoch 8/500
150/150 [==============================] - 0s 161us/step - loss: 1.1172 - acc: 0.1667
Epoch 9/500
150/150 [==============================] - 0s 119us/step - loss: 1.1043 - acc: 0.1267
Epoch 10/500


In [7]:
#Making Predictions
#With our trained model it’s easy to make predictions. First,
#we will make numpy print our probabilities in decimal form (removing the scientific notation).
#Then we will predict the first 10 samples in our X matrix.
np.set_printoptions(suppress=True)
neural_network.predict(X[0:10], batch_size=32, verbose=0)

array([[0.99812096, 0.00187896, 0.        ],
       [0.9973833 , 0.00261669, 0.        ],
       [0.9970573 , 0.00294272, 0.        ],
       [0.9966329 , 0.00336716, 0.        ],
       [0.99800056, 0.00199946, 0.        ],
       [0.9985178 , 0.00148221, 0.        ],
       [0.9967242 , 0.00327582, 0.        ],
       [0.9978643 , 0.00213572, 0.        ],
       [0.99573934, 0.00426063, 0.        ],
       [0.9976101 , 0.00238986, 0.        ]], dtype=float32)

In [13]:
#Our predicted class probabilities are:
print(Y[0:10])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]
