<a href="https://colab.research.google.com/github/souhirkammoun/MultilayerPerceptronExamples/blob/master/MLPWithIRISdataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#NB1 : import our data with the following python code.
#required library which holes the iris dataset
from sklearn.datasets import load_iris
import numpy as np
#load the iris dataset
iris = load_iris()
#our inputs will contain 4 features
X = iris.data[:, 0:4]
#the labels are the following
y = iris.target
#print the distinct y labels
print(np.unique(y))

#NB2: The last line prints the distinct labels for each of the 3 species. You should be seeing these labels:  [0 1 2] 

[0 1 2]


In [0]:
#NB3 :  In order for our classifier to work correctly we will first one hot encode our y vector 
#One Hot Encode our Y:
from sklearn.preprocessing import LabelBinarizer
encoder = LabelBinarizer()
Y = encoder.fit_transform(y)

In [3]:
#NB4 : Building our Model
#We will be now implementing a Multi-Layer Perceptron that contains 3 layers.
#Keras provides easy to use functionality to achieve this using its Sequential model.
#The Keras sequential model is a linear stack of layers. Keras provides different types of layers. 
#We will be using the Dense layer type which is a fully connected layer that implements the operation
#output = activation(dot(input, kernel) + bias). To train our network we will be using the Stochastic Gradient Descent optimizer.
from keras.models import Sequential #Sequential Models
from keras.layers import Dense #Dense Fully Connected Layer Type
from keras.optimizers import SGD #Stochastic Gradient Descent Optimizer
#NB5 : We will now create our network architecture. It will contain 3 layers. 

#Our first layer will have 4 inputs corresponding to the 4 features we will be utilizing from the iris dataset.
#For our second layer (hidden layer) we will be using 5 neurons.
#Our third layer, will provide our classifications. This layer contains 3 neurons, corresponding to the 3 classes that we are aiming to predict.
def create_network():
    model = Sequential()
    model.add(Dense(5, input_shape=(4,), activation='relu'))
    model.add(Dense(3, activation='softmax'))
        
    #stochastic gradient descent
    sgd = SGD(lr=0.001, decay=1e-6, momentum=0.9, nesterov=True)
    model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])
    return model

Using TensorFlow backend.


In [4]:
#NB6 :#Training our Model
#Once we have our model built, we compiled our model.
#To compile our model we need to provide a loss function and an optimizer.
#The optimizer we defined to be the Stochastic Gradient Descent with a learning rate of 0.001, decay of 0.000001 and momentum of 0.9. 
neural_network = create_network()
neural_network.fit(X,Y, epochs=500, batch_size=10)






Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/500





150/150 [==============================] - 1s 5ms/step - loss: 1.9630 - acc: 0.3533
Epoch 2/500
150/150 [==============================] - 0s 123us/step - loss: 1.1771 - acc: 0.6667
Epoch 3/500
150/150 [==============================] - 0s 107us/step - loss: 0.9654 - acc: 0.7067
Epoch 4/500
150/150 [==============================] - 0s 122us/step - loss: 0.9051 - acc: 0.8133
Epoch 5/500
150/150 [==============================] - 0s 122us/step - loss: 0.8521 - acc: 0.7267
Epoch 6/500
150/150 [==============================] - 0s 140us/step - loss: 0.7990 - acc: 0.6800
Epoch 7/500
150/150 [==============================] - 0s 113us/step - loss: 0.7475 - acc: 0.6800
Epoch 8/500
150/150 [==============================] - 0s 116us/step - loss: 0.6984 - acc: 0.6800
Epoch 9/500
150/150 [==============================] - 0s 119us/step - loss: 0.6562 - acc: 0.7400
Epoch 10/500


In [5]:
#Making Predictions
#With our trained model it’s easy to make predictions. First,
#we will make numpy print our probabilities in decimal form (removing the scientific notation).
#Then we will predict the first 10 samples in our X matrix.
np.set_printoptions(suppress=True)
neural_network.predict(X[70:100], batch_size=32, verbose=0)

array([[0.00008963, 0.404322  , 0.5955883 ],
       [0.00127478, 0.99826616, 0.00045911],
       [0.00007901, 0.4450053 , 0.5549157 ],
       [0.0004739 , 0.9759555 , 0.0235706 ],
       [0.00076642, 0.9986753 , 0.00055826],
       [0.00059037, 0.99881846, 0.00059114],
       [0.00027541, 0.9910521 , 0.00867252],
       [0.00012684, 0.8415233 , 0.15834993],
       [0.00041804, 0.9480745 , 0.05150741],
       [0.00916416, 0.9907968 , 0.00003899],
       [0.0017322 , 0.9959527 , 0.00231508],
       [0.00235125, 0.997074  , 0.00057475],
       [0.00174705, 0.9975624 , 0.00069061],
       [0.0000082 , 0.0603976 , 0.9395942 ],
       [0.00034018, 0.6622355 , 0.3374243 ],
       [0.00070746, 0.9855735 , 0.01371915],
       [0.00034287, 0.9958917 , 0.00376541],
       [0.00042905, 0.9756177 , 0.02395323],
       [0.00183217, 0.99418443, 0.00398339],
       [0.00099033, 0.97534573, 0.02366403],
       [0.00063772, 0.8979138 , 0.10144849],
       [0.00046207, 0.9786501 , 0.02088779],
       [0.

In [6]:
#Our predicted class probabilities are:
print(Y[70:100])

[[0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]]
